<?php
return [
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_type',
    'entity'  => 'OptionGroup',
    'cleanup' => 'never',
    'params'  => [
      'version'   => 3,
      'name'      => 'hubspot_update_type',
      'title'     => 'Hubspot Update Type',
      'data_type' => 'Integer',
      'is_active' => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_type_inbound',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_type',
      'value'           => 1,
      'name'            => 'inbound',
      'label'           => 'Inbound',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_type_outbound',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_type',
      'value'           => 2,
      'name'            => 'outbound',
      'label'           => 'Outbound',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_status',
    'entity'  => 'OptionGroup',
    'cleanup' => 'never',
    'params'  => [
      'version'   => 3,
      'name'      => 'hubspot_update_status',
      'title'     => 'Hubspot Update Status',
      'data_type' => 'Integer',
      'is_active' => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_status_pending',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_status',
      'value'           => 1,
      'name'            => 'pending',
      'label'           => 'Pending',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_status_completed',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_status',
      'value'           => 2,
      'name'            => 'completed',
      'label'           => 'Completed',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_status_failed',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_status',
      'value'           => 3,
      'name'            => 'failed',
      'label'           => 'Failed',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_status_conflicted',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_status',
      'value'           => 4,
      'name'            => 'conflicted',
      'label'           => 'Conflicted',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hubspot',
    'name'    => 'hubspot_update_status_discarded',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hubspot_update_status',
      'value'           => 5,
      'name'            => 'discarded',
      'label'           => 'Discarded',
      'is_active'       => 1,
    ],
  ],
];
