<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from hubspot/xml/schema/CRM/Hubspot/004-HubspotFormSubmission.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:59dac8614b690ab8361e7746843589db)
 */
use CRM_Hubspot_ExtensionUtil as E;

/**
 * Database access object for the HubspotFormSubmission entity.
 */
class CRM_Hubspot_DAO_HubspotFormSubmission extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_hubspot_form_submission';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique HubspotFormSubmission ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to HubSpotPortal
   *
   * @var int
   */
  public $hubspot_portal_id;

  /**
   * FK to HubSpotContact
   *
   * @var int
   */
  public $hubspot_contact_id;

  /**
   * @var string
   */
  public $guid;

  /**
   * Submission timestamp in HubSpot. VARCHAR because core does not support BIGINT.
   *
   * @var float
   */
  public $hubspot_timestamp;

  /**
   * @var longtext
   */
  public $submission_data;

  /**
   * ID of form submission status
   *
   * @var int
   */
  public $form_submission_status_id;

  /**
   * @var text
   */
  public $status_details;

  /**
   * @var timestamp
   */
  public $created_date;

  /**
   * @var timestamp
   */
  public $modified_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_hubspot_form_submission';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Hubspot Form Submissions') : E::ts('Hubspot Form Submission');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'hubspot_portal_id', 'civicrm_hubspot_portal', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'hubspot_contact_id', 'civicrm_hubspot_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique HubspotFormSubmission ID'),
          'required' => TRUE,
          'where' => 'civicrm_hubspot_form_submission.id',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'hubspot_portal_id' => [
          'name' => 'hubspot_portal_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to HubSpotPortal'),
          'where' => 'civicrm_hubspot_form_submission.hubspot_portal_id',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'FKClassName' => 'CRM_Hubspot_DAO_HubspotPortal',
          'add' => NULL,
        ],
        'hubspot_contact_id' => [
          'name' => 'hubspot_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to HubSpotContact'),
          'where' => 'civicrm_hubspot_form_submission.hubspot_contact_id',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'FKClassName' => 'CRM_Hubspot_DAO_HubspotContact',
          'add' => NULL,
        ],
        'guid' => [
          'name' => 'guid',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Form GUID'),
          'required' => TRUE,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_hubspot_form_submission.guid',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'hubspot_timestamp' => [
          'name' => 'hubspot_timestamp',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('HubSpot Timestamp'),
          'description' => E::ts('Submission timestamp in HubSpot. VARCHAR because core does not support BIGINT.'),
          'required' => TRUE,
          'precision' => [
            20,
            0,
          ],
          'where' => 'civicrm_hubspot_form_submission.hubspot_timestamp',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'submission_data' => [
          'name' => 'submission_data',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Submission Data (JSON)'),
          'required' => TRUE,
          'where' => 'civicrm_hubspot_form_submission.submission_data',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'form_submission_status_id' => [
          'name' => 'form_submission_status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Form Submission Status'),
          'description' => E::ts('ID of form submission status'),
          'required' => TRUE,
          'where' => 'civicrm_hubspot_form_submission.form_submission_status_id',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'hubspot_form_submission_status',
            'optionEditPath' => 'civicrm/admin/options/hubspot_form_submission_status',
          ],
          'add' => NULL,
        ],
        'status_details' => [
          'name' => 'status_details',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Status Details'),
          'required' => FALSE,
          'where' => 'civicrm_hubspot_form_submission.status_details',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'required' => TRUE,
          'where' => 'civicrm_hubspot_form_submission.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Modified Date'),
          'where' => 'civicrm_hubspot_form_submission.modified_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_hubspot_form_submission',
          'entity' => 'HubspotFormSubmission',
          'bao' => 'CRM_Hubspot_DAO_HubspotFormSubmission',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hubspot_form_submission', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hubspot_form_submission', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_hubspot_timestamp' => [
        'name' => 'index_hubspot_timestamp',
        'field' => [
          0 => 'hubspot_timestamp',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hubspot_form_submission::0::hubspot_timestamp',
      ],
      'index_form_submission_status_id' => [
        'name' => 'index_form_submission_status_id',
        'field' => [
          0 => 'form_submission_status_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hubspot_form_submission::0::form_submission_status_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
